analytics: {}
color:
  brandColors:
    - '#B8B8B8'
    - '#000000'
    - '#909090'
    - '#000000'
    - '#000000'
  brandStrength: 0.783344
  lightness: 0.461209
  rhythmicContrast: 0.126237
  saturation: 0.494138
cta: {}
layout_spectrum: 1
name: mellumphotography
opengraph: {}
purpose: {}
typography_spectrum: 0.610197
